import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const { data: sessionData } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (sessionData?.user) router.push("/notes");
  });

  return (
    <>
      <Head>
        <title>Notes | Sign In</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Content />
      </main>
    </>
  );
}

const Content = () => {
  return (
    <div className="hero min-h-screen bg-base-200">
      <div className="hero-content text-center">
        <div className="max-w-md text-lg">
          <h1 className="text-5x1 font-bold">Hello there</h1>
          <p className="py-6">
            To use this note taking application, you need to sign in!
          </p>
          <button className="btn btn-primary" onClick={() => signIn()}>
            Sign In
          </button>
        </div>
      </div>
    </div>
  );
};
