import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import { BsFillTrashFill } from "react-icons/bs";
import { Header } from "~/components/Header";
import { NoteCard } from "~/components/NoteCard";
import { NoteEditor } from "~/components/NoteEditor";
import { StyledInput } from "~/components/StyledInput";
import { Note } from "~/server/api/routers/note";
import { Topic } from "~/server/api/routers/topic";
import { api } from "~/utils/api";

export default function Home() {
  const { data: sessionData } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (!sessionData?.user) router.push("/");
  });

  return (
    <>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
}

const Content = () => {
  const [displayedTopics, setDisplayedTopics] = useState<Topic[] | undefined>(
    undefined
  );

  const [selectedTopic, setSelectedTopic] = useState<Topic | null>(null);
  const [selectedNote, setSelectedNote] = useState<Note | null>(null);

  const [noteTitle, setNoteTitle] = useState("");
  const [noteContent, setNoteContent] = useState("");

  const dialogRef = useRef<HTMLDialogElement>(null);

  const { data: sessionData } = useSession();

  const { data: topics, refetch: refetchTopics } = api.topic.getAll.useQuery(
    undefined,
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => setDisplayedTopics(data),
    }
  );

  const { data: notes, refetch: refetchNotes } = api.note.getAll.useQuery(
    {
      topicId: selectedTopic?.id ?? "",
    },
    {
      enabled: sessionData?.user !== undefined && selectedTopic !== null,
    }
  );

  const createTopicMutation = api.topic.create.useMutation({
    onSuccess: (topic) => {
      refetchTopics();
      setSelectedTopic(topic);
    },
  });

  const deleteTopicMutation = api.topic.delete.useMutation({
    onSuccess: () => {
      refetchTopics();
      setSelectedTopic(null);
    },
  });

  const createNoteMutation = api.note.create.useMutation({
    onSuccess: () => refetchNotes(),
  });

  const deleteNoteMutation = api.note.delete.useMutation({
    onSuccess: (note) => {
      refetchNotes();
      if (note.id === selectedNote?.id) {
        setSelectedNote(null);
        setNoteTitle("");
        setNoteContent("");
      }
    },
  });

  const updateNoteMutation = api.note.update.useMutation({
    onSuccess: () => {
      refetchNotes();
      setSelectedNote(null);
    },
  });

  const renderTopics = () => {
    return displayedTopics?.map((topic) => (
      <li key={topic.id} className="">
        <a
          href="#"
          className={`flex max-w-full justify-between ${
            topic.id == selectedTopic?.id ? "active" : ""
          }`}
          onClick={(e) => {
            e.preventDefault();
            setSelectedTopic(topic);
            setSelectedNote(null);
            setNoteContent("");
            setNoteTitle("");
          }}
        >
          <span className="flex-1 truncate">{topic.title}</span>
          <BsFillTrashFill
            size={14}
            onMouseOver={(e) => e.currentTarget.classList.add("text-error")}
            onMouseLeave={(e) => e.currentTarget.classList.remove("text-error")}
            onClick={() => dialogRef.current?.showModal()}
          />
        </a>
      </li>
    ));
  };

  const renderNotes = () => {
    return notes?.map((note) => (
      <div key={note.id} className="mt-5">
        <NoteCard
          note={note}
          onDelete={() => deleteNoteMutation.mutate({ id: note.id })}
          onEdit={() => {
            setNoteContent(note.content);
            setNoteTitle(note.title);
            setSelectedNote(note);
          }}
        />
      </div>
    ));
  };

  return (
    <>
      <div className="mx-5 mt-5 grid grid-cols-4 gap-5">
        <div className="col-span-4 px-2 md:col-span-1">
          <StyledInput
            type="text"
            placeholder="Create topic"
            required={true}
            requiredMessage="Topic title cannot be empty"
            onEnter={(text) => createTopicMutation.mutate({ title: text })}
          />

          <div className="divider"></div>

          <StyledInput
            type="text"
            placeholder="Search"
            onChange={(text) => {
              setDisplayedTopics(
                topics?.filter((topic) =>
                  topic.title.toLowerCase().includes(text.toLowerCase())
                )
              );
            }}
            onClear={() => {
              setDisplayedTopics(topics);
            }}
          />

          <div className="divider"></div>

          <div className="menu-title">
            <div className="flex gap-2">
              <span className="flex-1">Topics</span>
              <span className="flex-none">{displayedTopics?.length}</span>
            </div>
          </div>

          <ul className="menu rounded-box h-40 flex-nowrap overflow-y-auto bg-base-100 px-0 ">
            {renderTopics()}

            <dialog ref={dialogRef} className="modal">
              <form method="dialog" className="modal-box">
                <h3 className="text-lg font-bold">Delete topic</h3>
                <p className="py-4">
                  Are you sure you want to delete this topic? All related notes
                  will be deleted as well.
                </p>
                <div className="modal-action">
                  <button
                    className="btn btn-error"
                    onClick={() =>
                      deleteTopicMutation.mutate({ id: selectedTopic!.id })
                    }
                  >
                    Yes
                  </button>
                  {/* <!-- if there is a button in form, it will close the modal --> */}
                  <button className="btn">No</button>
                </div>
              </form>
            </dialog>
          </ul>
          <div className="divider"></div>
        </div>
        <div className="col-span-4 px-2 md:col-span-1">
          {selectedTopic && (
            <>
              <NoteEditor
                title={noteTitle}
                code={noteContent}
                setTitle={setNoteTitle}
                setCode={setNoteContent}
                isEditing={selectedNote ? true : false}
                onSave={({ title, content, isEditing }) => {
                  if (isEditing) {
                    updateNoteMutation.mutate({
                      id: selectedNote!.id,
                      title,
                      content,
                    });
                  } else {
                    createNoteMutation.mutate({
                      title,
                      content,
                      topicId: selectedTopic.id,
                    });
                  }
                }}
                onCancel={() => setSelectedNote(null)}
              />
              {renderNotes()}
            </>
          )}
        </div>
      </div>
    </>
  );
};
